### PR TITLE
Version 2

### PR DESCRIPTION
**Pull request by cmpotts**
Preparing for version 2 release. Please review this request, test the simulation, and report back with feedback. This version will be pushed out to participants for a user study when ready so we want to make sure it is good to go.

### CODE REVIEW

**Comment by SashaZd** [comment]
Agents aren't using the roads or traversing square by square to move. Instead, they seem to just do a, "as the crow flies" jump to the next location. Need to change the routing mechanic for agents.

**Comment by movinglinguini** [comment]
- After clicking an agent, I can't consistently get the agent window to go away.
- I see some old references in the script, like types.ts 
- The game's pulling from the data under the AugustDemo folder, not just the Data folder.
- Adding a new agent to the AugustDemo folder was fine.
- Adding a new location to the AugustDemo folder was fine.
- I expect the Connections field on locations is going to confuse participants

**Comment by alexo1110** [comment]
Thanks @movinglinguini for pointing out that the SimManager was still being routed to the AugustDemo folder, that is fixed now.

Do you have any suggestions for the "Connections" field of locations? The intent was to move away from a strictly coordinate grid-based system and towards a graph system for performance, but I see your point. Maybe if its an issue that comes up during the usability testing we could instead pivot to a grid-based user interface that is translated to a graph in the backend on startup? It also might be something that could benefit from a frontend system to allow a "pretty" editor for adding in nodes and dragging between them to add connections, but obviously we don't have anything like that in place right now.

Also @SashaZd as far as I know the Unity frontend has obstacle-avoidance pathfinding implemented, but my guess is that it isn't identifying unconnected adjacent nodes as obstructed. @Prismly, @jacksonpeck, or @tzriga would likely know better than me about this.

**Comment by SashaZd** [comment]
> Do you have any suggestions for the "Connections" field of locations? The intent was to move away from a strictly coordinate grid-based system and towards a graph system for performance, but I see your point. Maybe if its an issue that comes up during the usability testing we could instead pivot to a grid-based user interface that is translated to a graph in the backend on startup? It also might be something that could benefit from a frontend system to allow a "pretty" editor for adding in nodes and dragging between them to add connections, but obviously we don't have anything like that in place right now.

I like the graph-based, but I think we can build graph connections after the fact (based on the map/roads/etc)? Maybe we could use a random-walk algorithm between the locations described in the JSON, and then have roads/connections based on that? I think I have code for that someplace. Alternatively, even just connecting them right now with straight-right-angled roads works and is preferable to the JSON defining the connections. Let's talk about this in the next meeting. @cmpotts and @arnurb what do you think?

**Comment by arnurb** [comment]
I favor grid-based for the speed of implementation. Graph-based will
require a lot more UI work and it will take time to implement before it is
ready to give in the hands of users.

- Arnav

**Comment by movinglinguini** [comment]
> Thanks @movinglinguini for pointing out that the SimManager was still being routed to the AugustDemo folder, that is fixed now.
> 
> Do you have any suggestions for the "Connections" field of locations? The intent was to move away from a strictly coordinate grid-based system and towards a graph system for performance, but I see your point. Maybe if its an issue that comes up during the usability testing we could instead pivot to a grid-based user interface that is translated to a graph in the backend on startup? It also might be something that could benefit from a frontend system to allow a "pretty" editor for adding in nodes and dragging between them to add connections, but obviously we don't have anything like that in place right now.
> 
> Also @SashaZd as far as I know the Unity frontend has obstacle-avoidance pathfinding implemented, but my guess is that it isn't identifying unconnected adjacent nodes as obstructed. @Prismly, @jacksonpeck, or @tzriga would likely know better than me about this.

Yeaaaa... I know the connections was effectively to bake paths into the map so that agents aren't recalculating paths every time they move between locations. Would it be a big haul to calculate those connections at runtime, a la @SashaZd's idea?

**Review by SashaZd — APPROVED** [review]

**Pull request merged**
